### PR TITLE
Feature/software/29

### PR DESCRIPTION
**Pull request by eslamdyab21**
- added a test case of a web camera and a printed qr code
- renamed the Graduation Project Documentation to Graduation-Project-Documentation to avoid paths with spaces problem

### CODE REVIEW

**Review by mennamamdouh — APPROVED** [review]
great

**Comment by Islamoo7** [comment]
The QR code reads correctly but we need to manipulate the size of the printed QR (about 2x2 cm2) code to accommodate the height of the camera.

**Comment by eslamdyab21** [comment]
> The QR code reads correctly but we need to manipulate the size of the printed QR (about 2x2 cm2) code to accommodate the height of the camera.

Ok, will scale the printed QR size down.

**Comment by gehadelkoumy** [comment]
I have resized the QR code image @Islamoo7

**Comment by Islamoo7** [comment]
great job.

**Pull request closed without merging**
