### PR TITLE
Database - Merge the code of the database with the documentation of the creation process

### PR DESCRIPTION
**Pull request by mennamamdouh**
In this pull request:
- The database of the system has been created. It contains:
    - Different tables which integrate with the website, web application, and the robots in the warehouse
    - Columns of each table and their constraints
    - Some triggers to facilitate the writing and updating processes
- Main information of the database has been documented

### CODE REVIEW

**Review by eslamdyab21 — APPROVED** [review]
> In this pull request:
> 
> * The database of the system has been created. It contains:
>   
>   * Different tables which integrate with the website, web application, and the robots in the warehouse
>   * Columns of each table and their constraints
>   * Some triggers to facilitate the writing and updating processes
> * Main information of the database has been documented

Nice work Menna !

**Comment by eslamdyab21** [comment]
@mennamamdouh can you take a copy of the `database-creation@23.md` file and put it as a readme file to the issue folder? 
also we don't need the `Graduation Project Documentation` anymore.

**Comment by mennamamdouh** [comment]
@eslamdyab21 ok done, I've added the readme file and deleted the Graduation Project Documentation too.

**Review by eslamdyab21 — APPROVED** [review]

**Review by Islamoo7 — COMMENTED** [review]
Great job.

**Review by Islamoo7 — APPROVED** [review]

**Review by eslamdyab21 — APPROVED** [review]

**Review by eslamdyab21 — APPROVED** [review]

**Pull request merged**
