### PR TITLE
Feature/software/29

### PR DESCRIPTION
**Pull request by gehadelkoumy**
- resized Qr code image to half

### CODE REVIEW

**Review by eslamdyab21 — APPROVED** [review]
Great work Gehad!

**Review by mennamamdouh — CHANGES_REQUESTED** [review]
Can you please explain to me why do we need to resize the qr image to half, Gehad?

**Comment by gehadelkoumy** [comment]
The QR code image needs to be small in order for camera to detect it from a small height 
It doesn't have to be resized to half, it could be any smaller value.

**Comment by mennamamdouh** [comment]
Well I got you. Great work by the way 👏🏻

**Review by mennamamdouh — APPROVED** [review]

**Pull request merged**
